spring.application.name=streaming-service

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.group-id=streaming-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.netflix.streamingservice.event.VideoEncodedEvent

spring.server.port=8084

aws.access-key=${AWS_ACCESS_KEY:your-access-key}
aws.secret-key=${AWS_SECRET_KEY:your-secret-key}
aws.region=${AWS_REGION:ap-south-1}
aws.s3.bucket-name=${AWS_BUCKET_NAME:your-bucket-name}
aws.s3.presigned-url-expiry=60

management.endpoints.web.exposure.include=health,info   