spring.application.name=video-service

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
spring.server.port=8082

aws.access-key=${ACESS_KEY}
aws.secret-key=${SECRET_KEY}
aws.region=${REGION}
aws.s3.bucket-name=${BUCKET_NAME}

management.endpoints.web.exposure.include=health,info